# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
# Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
# Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.


from time import time
start = time()
import math

def is_perfect_square(num):
    sr = math.sqrt(num)
    if sr-math.floor(sr) == 0:
        return True
    else:
        return False

def is_triangle(num):
    if is_perfect_square(8*num+1) is True:
        return True
    else:
        return False

def is_pentagonal(num): #NOT WORKING
    if (math.sqrt(24*num+1))%6==5 is True:
        return True
    else:
        return False

def is_hexagonal(num):
    if (math.sqrt(8*num+1)+1)%4==0:
        return True
    else:
        return False

done = False
i = 2
while not done:
    pent = i*(3*i-1)/2
    if is_hexagonal(pent) is True and pent !=40755:
        if is_triangle(pent) is True:
            done = True
    i+=1
print(pent)





end = time()

print("TIME:",end-start)









